export const enum OrangeHrmEndpoint {
  LOGIN_PAGE = "auth/login",
  DASHBOARD_PAGE = "dashboard/index",
  PIM_PAGE = "pim/viewEmployeeList",
  ADD_EMPLOYEE_PAGE = "pim/addEmployee",
  EMPLOYEE_DETAILS_PAGE = "pim/viewPersonalDetails/empNumber",
  RECRUITMENT_PAGE = "recruitment/viewCandidates",
  VACANCY_PAGE = "recruitment/viewJobVacancy",
  ADD_VACANCY_PAGE = "recruitment/addJobVacancy",
  TIME_PAGE = "time/viewEmployeeTimesheet",
  PROJECT_PAGE = "time/viewProjects",
  CUSTOMER_PAGE = "time/viewCustomers",
  ADD_PROJECT_PAGE = "time/saveProject",
  ADD_CUSTOMER_PAGE = "time/addCustomer",
}
